language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- pytest --cov groupme_bot
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: pI7EQh5HrzpOpL0lI1MtUZSCWQ1yY6Z2B3BuuRh19izPciPp1dHxMacA06nGISF+Kb5z8N+iTfTg5ujX7wZBefDJS4ZSKgVuzfZ5z85l9we5TPGyF3ovEI5O/yDYV+Lnt8k7fVJcUbYBcgryl06I5/bOA6RtXJFF9SWND9aUgTiDA1T5aoCT0xFXMSNAe518QwYjEOgK4w4sTYrZj7cmfKRoHEgXx0K+K+t4doH0QHjJgnjCH8V2CcLKghfrj+66nbHaVLokZ6g95OWfR18bpL+6725vpUQNQZMEzn5xQUQ8AfJ/5BPlp2//tkMsOCx/ZCkq8TM/GMllh//4O/cyxPgFZhwSWp40FgaV9vbgBRXdai2bUMK+S2jmWhZuOPyVxQvcOm6mR7JDtT3cY9xwPVI5xvGiRq7Kj4mfTTCRrHdEnoG1c92v4jhWkGxY0jzNWCPNFRyF86iYjl0+T4qPMR4gz07vCR20qPJ7zdJMqS1kYMpLJl/+okp3LyANwVSeGKCPYCY7Fbg82oOp87WtQ9CtB2g0DWLooBHK3arXxE8rWnlMCLehLaBmHUtHYxVspbG76SNHjggTR5TWJjzGQaidd13mvDVD72KiuSf0wuIwR5TFX1nEULayVvSZJo6dieNNqaWBfa6EMW8YLNERxGrMihv3TMJyMCIT1MNLlOs=
