language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- pytest --cov groupme_bot
- zappa update dev
after_success:
- coveralls
env:
  global:
  - secure: FxrQfXmAjX8FxcUn58TFm105Nk6bXt08vNk0tP6ePFQ1/YKzwoWfdaIdvQShYyQhl1nwlPc5boOjD3C6ucr0ZW6X1xf+Kej6BOsfFmz19RqBGWVixIUiK9u1UERLlJ9D5JBPtNsV6bjY0N2613r334U4fPOrrW0/NbJi45aX23wDn014gQg+y/6Z6pNiiIOjpxC+gwuXv8E21bbclSkzaQWHwxwfuOCJD90/esDh+nmw7vzDBnyadAkJ8TvVmyitAU3ML8Q8XAwA/wiuromMVML9sVBTM0NHMmsenwX+dy/R2NasUAQGWrJRPEBebELyDzwR7UnA7poMTGjEqTKWv6J5eoDatFkvakvrMAKZJAd3AbXdWy5cGhwujzLvTdKggEPOz+H3dz0bDVQLM7A+xhNdcbP6/1ELgp1DhNAzCKrkMvf51/7nUUOeNA07hJK1RqbY1pctKEBF3DURa79F4ql50JV0pCTB5m+8z9hd5oC7IwPqEgcxVgM3NB38wVHeBWH/DIwhZ0/uHKiT75ozwSL48F1KpVshPWWYUx5j+NoDoKjbb4jxGm4iJeYBeGv5os7VMlqkVQMzCUPe1wAe6JYT34WboCDxpzG+EGxJHnZARBgX2Yug+uJiZVr66WZihcKO4mzD50zn9gSTvV32Dj+YC7GsdIeDyrSSTB53d4o=
  - secure: bCjrkn/ZR1S075Sa0X/fVMVMQVcX6FoY5DmepWBqNOb2AzjT7P0XHQmBicqc2pZwtdOG5FKS/ctnxqtkoL5aGcIzjMsL5bLqTU+chc6yjAByj2fPkgDxEMMhcIR7CC3mm54PJ8ZwJ2fu0f24OS+jqSRjGuk/aaNUP5w8gEb5LovQYkWIHj8CpoVwqiYg94sDmi+BX9ga9T/Bk0oTHLs9NPx5a+kgBWGK8C8u0dZmhla73g+YtWHEowT+5I4nfJ89fHA5+dwTy+pXLqhYOLgIjc9SqdGmrzS2j93iZS7fxrGGnqAFAJZwvTM4QdAtoL//DNCzEUTlJcxwPOGd+9RW6GTIcU+MtFfoLoExyTJGFMLHvc3BrYW8PVhxWYe0EC1OduyQ7C75i3nYAsuzCnCsNfQmstwURSCSkveEk0O3ZO5sB98MYQcYkp7FusKkLUeOg3cDsX7oOvaz1LdT1vVdnNbxzTOICoYKjg+9auMCXoQVzV9+rStBhz3NZZDTp2TFwj3uTbib97ZnDi7tbr0MTIa9Rxw5mhANhuBgfOKsotcw1izcg4PS99loZXF8E1fboPqJoSdegLcUClOOnKwf3JFEjjHDZlKLcWxtdrDwAewu7S8LlHCa6Hpq/bdlDTN6FPGc7tyt0QBgL9QQaAaoH+Zhk+9floUJSzeGxjJn3jY=
