language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- pytest --cov groupme_bot
- zappa update dev
after_success:
- coveralls
env:
  global:
  - secure: ud6pQurhSGo+eCDqlyVmUiAnqomY1nmRPvokpn61v8f+SJ2A/SDmZ91v1IoWZkObnUSP4KHPevPvyKXC3x3J2wfeBCzYqT4Zq8iasYn3Esddaqzjy1HUlRrCa5XjWtaYWtGxj9QJgWuY+A7jagtPIKAJzbV8MtN2DHw5sc9QdHeVlRivvX8SinUMauqJ34UstisHkI6gkrhYoWIkZ5LrjoVe/WbnIqT2ncWJj4fp4q80zdcXxVCFrl64u71jpW6eXMGDQ7J1ofC86YfbZFMF11w7pCol8h+6i1HOJa674h3AJF5e468zP/+v3yU0otiRPf61mEsPpyso8NOecsXr8bE+gR6jh4rhOFfIYw76UIag+iVDHNOpa3TX+4L30i+a1w8OnHul4PR+1yjAQcDlYavVuTIaa6qiwsRvqbVdCSAYSLlKl5Gm2YRa8tr79pJSbO0qaxnCt0IjOJq0iT7w+jb7jb0XdT5DK1v3ZudDKq8vHsb7R8nOmLc/MomzeTvbnIUYMoDJCsF7+bpBfCeX9xsB+7QNGuwxCPD1Ua5qFBLKMITQitzxa0P/DkAcPHAnnExA7jKhrXYcOlG3sNbwE5NxsLfUkgM+HFieZ6Bmbl6Irzj59L+C3xONvtF+UXCEdiCdc+MR87GWw8eGFFeSErtRUWzKwJ8c4ytDJYuTvIQ=
  - secure: iBlbt3yCm310iHw7PA1XN0ZD6BF1LvoEH/EvjavqnNLnpbsqsp8XiTCFbyD6Vg/HXZhfD0kI7YnCfRO/uyI7TViT7B7N89PH1RlkTk8CKu1PBAVw2xx+W2Twb7PWPzM5BHdm/ZlN3bltmQQQxJCXtKMeCZtIjLaHXAK9C6lBHlwPMbEqSUuL+LRpNR+LJCmGcAD3by0WcC1ex1P/ipYFQdqRy6Vi6MB/X209DsqHTcOcdXoiugTC+tVoDCJBRDY9jtgahz0RO/pXJm4Ih1hcVCKGY0hUVc6ogGzBX3tfxDMoyBJVcBVX+zMLZuvRsvmbVFjh52+ac+6aVTw7T2zX9v+AVsM4KFb9K5OKvnKu3b/s6LJAOLjb7NOLl7Hy3qsxgPN97Q9d/ks8pA5cMZtJQmIxLBNL45g1gBWAlRZN1mzyLqRyu7TL/OoKUjmdi34QoGenMv9affs6nUElgq7UCijlx4VQ4RXf3bE8JGRX+ifQlTNf+UUIw7VMe+f4pIoU4LLomjzq42jdseZGV0ZJqtk2sy/1BsISoxM37cvFHh8cDHc8Uqc9rnW7ZO5mMmxcjyLRi1cjiWSc6ull4bOuhRuvIxP7B1BfgnvGuLu/l6D28JVx6Z+QShsR/+se7KPKKRiMxZD7dpYABfDP0FjWpIAgWKw2iCT8NZztRxIGUJI=
